### ISSUE TITLE
Recommended approach for window resizing?

### ISSUE THREAD

**Issue by mrodrig** [arkokoley/pdfvuer#13]
Hi,

Thanks for the awesome Vue component! One thing that I noticed is that when resizing the window, the generated PDF doesn't automatically resize. It seems like there's possible an event that could be watched to have the PDF resize, but I was wondering if there's a recommended approach or something that would need to be done in this component to support that?

The public demo has the same behavior as what I'm seeing in my app. If you open it while the browser is fully expanded and then make the browser's width narrower (eg. locking the browser to either half of the screen), then the PDF remains at its original size. Refreshing the page causes the PDF to be displayed at the correctly scaled size.

Thanks!

**Comment by arkokoley** [comment]
Hi @mrodrig,

Glad that you like this component!

Coming to your question, the auto-resizing functionality was missing because I didn't need it for my original use case. The required events was indeed available through the [vue-resize-sensor](https://github.com/FranckFreiburger/vue-resize-sensor) component. 

I have now updated the component where you can enable auto-resizing using a resize prop. Please have a look at the README for the exact details.

https://github.com/arkokoley/pdfvuer/blob/master/README.md#resize-boolean---default-false

**Comment by mrodrig** [comment]
Hi @arkokoley,

Thanks for the quick response and for the new resize functionality! It's working great!

Much better than my hacky debounced page reload on window resize events 🙂

Thanks again!
