### ISSUE TITLE
How to print PDF?

### ISSUE THREAD

**Issue by thyagodias** [arkokoley/pdfvuer#22]
How can I use `intent` to print PDF. - Rendering intent, can be 'display' or 'print' (default value is 'display'). 
Or is there another way?

**Comment by tartinesKiller** [comment]
pdf.js's `intent` is used only to determine if annotations must be fetched:
```
 * @property {string} intent - Determines the annotations that will be fetched,
 *                    can be either 'display' (viewable annotations) or 'print'
 *                    (printable annotations).
 *                    If the parameter is omitted, all annotations are fetched
```
from https://mozilla.github.io/pdf.js/api/draft/display_api.js.html
In order to print the pdf, you can use https://printjs.crabbly.com/
Note that the printing dialog will open only in Chrome (at the time of writing), Firefox will open the PDF in its viewer, which have a print functionality. 
I'm using it in production, no problems so far.
